name: Semantic PR title
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_call:
    inputs:
      runner:
        description: Runner label to use for the job
        type: string
        default: ubuntu-24.04

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  semantic-pr-title:
    name: Check Semantic PR title
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    timeout-minutes: 10
    permissions:
      pull-requests: read
    steps:
      - name: Check PR titile
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
